import ApiClientBase from './ApiClientBase';

/**
 * Class for interacting with Contest specific features of the Nexosis API.
 * Note that the endpoint called by this client is not available under the community plan.
 * Please upgrade and use the Paid Subscription key in order to use this client.
 */
export default class ContestClient extends ApiClientBase {

    /**
     * Get detailed data science information generated by a session.
     * 
     * @param {string} sessionId  - The session to retrieve contest information from
     */
    getContest(sessionId: string) {
        return this._apiConnection.get(`sessions/${sessionId}/contest`, this.FetchTransformFunction);
    }

    /**
     * Get a specific contestant algorithm, and the test data used in scoring the algorithm.
     * 
     * @param {string} sessionId  - The session to retrieve contestant information from
     * @param {string} contestantId - The contestant to retrieve information from
     */
    getContestant(sessionId: string, contestantId: string) {
        return this._apiConnection.get(`sessions/${sessionId}/contest/contestants/${contestantId}`, this.FetchTransformFunction);
    }

    /**
     * Gets the champion of a contest, and the test data used in scoring the algorithm.
     * 
     * @param {string} sessionId  - The session to retrieve champion information from
     */
    getChampion(sessionId: string) {
        return this._apiConnection.get(`sessions/${sessionId}/contest/champion`, this.FetchTransformFunction);
    }

    /**
     * Gets the selection criteria that is used to determine which algorithms were executed.
     * 
     * @param {string} sessionId  - The session to retrieve champion information from
     */
    getSelection(sessionId: string) {
        return this._apiConnection.get(`sessions/${sessionId}/contest/selection`, this.FetchTransformFunction);
    }

    /**
     * Lists the contestant algorithms which were executed for this contest.
     * 
     * @param {string} sessionId  - The session to retrieve champion information from
     */
    listContestants(sessionId: string) {
        return this._apiConnection.get(`sessions/${sessionId}/contest/contestants`, this.FetchTransformFunction);
    }
}